# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436830525df8dcf9b6376ab9ba8fdf188fa9dff25cbd7b5165d6a07be942c63b0a6c45753fd225bcbfb49a96ee3153fdacfedbfb374859b4ccf02d88a03963a3

test:
  secret_key_base: 67a3eba550ae586c3d3c3f5c83e74fa48c200d2a9661534c54b2a723779087138515173dac93f8cc555481595c4b4d1991dfc1b738c05fc2265fb2fcd34ebb08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
